apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend-1
  template:
    metadata:
      labels:
        app: backend-1
    spec:
      containers:
      - name: backend-app
        image: jaimehenao8126/backend:latest
        ports:
        - containerPort: 80